# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20180210_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='alg_description',
            field=models.CharField(max_length=1500),
        ),
    ]
